version: "3.9"
services:
  sftp:
    image: atmoz/sftp:latest
    container_name: local_sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data/nikhil/upload:/home/nikhil/upload
    command: nikhil:password:1001
    restart: unless-stopped
